---
apiVersion: v1
kind: Service
metadata:
  name: prom-expose
spec:
  type: NodePort
  selector:
    app: prom
  ports:
  - port: 9090
    nodePort: 31000
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  labels:
    app: prom
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prom/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: prom-pvc
    labels:
        app: prom
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: manual
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: prom-config
    labels:
        app: prom

data:
    prometheus.yml: |-
        global:
            scrape_interval: 15s
            evaluation_interval: 15s
        scrape_configs:
            - job_name: 'prometheus'
              static_configs:
              - targets: ['localhost:9090']
            - job_name: 'node1'
              static_configs:
              - targets: ['192.168.40.133:9100']
            - job_name: 'docker'
              static_configs:
              - targets: ['192.168.40.133:9323']
            
              
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: prom-deployment
    labels:
        app: prom
spec:
    replicas: 1
    selector:
        matchLabels:
            app: prom
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: prom
        spec:
            containers:
                - image: prom/prometheus
                  name: prom-container
                  ports:
                    - containerPort: 9090
                  volumeMounts:
                    - name: prom-config-volume
                      mountPath: /etc/prometheus
                    - name: prom-data
                      mountPath: /prometheus
            securityContext:
                runAsUser: 0
            
            volumes:
                - name: prom-config-volume
                  configMap:
                    name: prom-config
                - name: prom-data
                  persistentVolumeClaim:
                    claimName: prom-pvc
                
---

    


